version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      # --ignore-scripts makes the postinstall script not run, which is good
      # because we want to do that in a separate build step.
      - run: yarn install --ignore-scripts

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn run prettier-check
      - run: yarn run server-build
      - run: yarn run frontend-build
